site_name: Unofficial Daggerheart System for FoundryVTT
short_name: Foundry UDH Sytem Documentaion

docs_dir: documentation/docs
nav:
  - Home: index.md
  - Systems:
    - Rolling:
      - Duality Rolls: systems/rolling/duality-rolls.md
      - Duality Dice Command: Duality Dice Command.md
      - Advantage & Disadvantage: systems/rolling/advantage-disadvantage.md
      - NPC Rolls: systems/rolling/npc-rolls.md
    - Damage:
      - Damage Application: systems/damage/damage-application.md
      - Damage Dialog: systems/damage/damage-dialog.md
    - Resources:
      - Hope, Fear & Stress: systems/resources/hope-fear-stress.md
      - Resource Enrichment: systems/resources/resource-enrichment.md
  - UI:
    - Actor Sheets: ui/actor-sheets.md
    - Item Sheets: ui/item-sheets.md
    - Token Counter: ui/token-counter-ui.md
    - Top Bar: ui/top-bar-ui.md
    - Countdown Trackers: ui/countdown-trackers.md
    - Domain Ability Sidebar: ui/domain-ability-sidebar.md
    - Tracker Notification Bubbles: ui/tracker-notification-bubbles.md
    - Hover Distance: ui/hover-distance.md
  - Mechanics:
    - Modifiers Manager: Modifiers Manager.md
    - Equipment System: mechanics/equipment-system.md
    - Range Measurement: mechanics/range-measurement.md
    - Dice Customization: mechanics/dice-customization.md
  - Technical:
    - Chat Commands: technical/chat-commands.md
    - Text Enrichers: technical/text-enrichers.md
    - API Reference: technical/api-reference.md
    - Macros: technical/macros.md
  - Data Models:
    - Actor Model: data-models/actor-model.md
    - Item Model: data-models/item-model.md
    - System Settings: data-models/system-settings.md
extra_css:
  - overrides/assets/stylesheets/custom.css

# theme: readthedocs
theme:
    logo: overrides/assets/codex.svg
    name: 'material'
    custom_dir: documentation/docs/overrides
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks

extra_javascript:
  # - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  # - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://unpkg.com/mermaid/dist/mermaid.min.js 
